import * as TbaApi from './tbaApi';
import * as TbaRequest from './tbaRequest';

export type Tinyint = 0 | 1;

export type MatchEntry = {
    id:                              number;
    event_key:                       TbaApi.EventKey;
    team_number:                     number;
    scouter_initials:                string;
    comp_level:                      TbaApi.Comp_Level;
    match_number:                    number;
    robot_position:                  TbaRequest.RobotPosition;
    auton_leave_starting_line:       Tinyint;
    auton_coral_scored_l4:           number;
    auton_coral_missed_l4:           number;
    auton_coral_scored_l3:           number;
    auton_coral_missed_l3:           number;
    auton_coral_scored_l2:           number;
    auton_coral_missed_l2:           number;
    auton_coral_scored_l1:           number;
    auton_coral_missed_l1:           number;
    auton_algae_scored_net:          number;
    auton_algae_missed_net:          number;
    auton_algae_scored_processor:    number;
    teleop_coral_scored_l4:          number;
    teleop_coral_missed_l4:          number;
    teleop_coral_scored_l3:          number;
    teleop_coral_missed_l3:          number;
    teleop_coral_scored_l2:          number;
    teleop_coral_missed_l2:          number;
    teleop_coral_scored_l1:          number;
    teleop_coral_missed_l1:          number;
    teleop_algae_missed_net:         number;
    teleop_algae_scored_net:         number;
    teleop_algae_scored_processor:   number;
    endgame_coral_intake_capability: string;
    endgame_algae_intake_capability: string;
    endgame_climb_successful:        Tinyint;
    endgame_climb_type:              string;
    endgame_climb_time:              string;
    overall_robot_died:              Tinyint;
    overall_defended_others:         Tinyint;
    overall_was_defended:            Tinyint;
    overall_defended:                string;
    overall_defended_by:             string;
    overall_pushing:                 number;
    overall_defense_quality:         number;
    overall_counter_defense:         number;
    overall_driver_skill:            number;
    overall_major_penalties:         number;
    overall_minor_penalties:         number;
    overall_penalties_incurred:      string;
    overall_comments:                string;
    robot_appeared:                  Tinyint;
};
export type StrategicEntry = {
    id:               number;
    event_key:        TbaApi.EventKey;
    team_number:      number;
    scouter_initials: string;
    comp_level:       TbaApi.Comp_Level;
    match_number:     number;
    robot_position:   TbaRequest.RobotPosition;
    comments:         string;
};
export type PitDataEntry = {
    id:                          number;
    event_key:                   string;
    team_number:                 number;
    scouter_initials:            string;
    robot_weight:                number;
    drive_train_type:            string;
    propulsion_motor_type:       string;
    number_of_propulsion_motors: number;
    wheel_type:                  string;
    fuel_intake_location:        string;
    intake_type:                 string;
    intake_width:                string;
    max_fuel_capacity:           number;
    max_shot_range:              string;
    trench_capability:           Tinyint;
    climb_during_auto:           Tinyint;
    can_climb_l1:                Tinyint;
    can_climb_l2:                Tinyint;
    can_climb_l3:                Tinyint;
    pit_organization:            number;
    team_safety:                 number;
    team_workmanship:            number;
    gracious_professionalism:    number;
    any_electrical_issues:       string;
    comments:                    string;
};

export type PitPictureEntry = {
    id:                        number;
    event_key:                 TbaApi.EventKey;
    team_number:               number;
    scouter_initials:          string;
    robot_image_uri:           string;
}

export type PitDataFullEntry = PitDataEntry & { robot_image_uri: string };
