import * as TbaApi from './tbaApi';
import * as TbaRequest from './tbaRequest';

export type Tinyint = 0 | 1;

export type MatchEntry = {
    id:                              number;
    match_event:                     TbaApi.EventKey;
    team_number:                     number;
    scouter_initials:                string;
    comp_level:                      TbaApi.Comp_Level;
    match_number:                    number;
    robot_position:                  TbaRequest.RobotPosition;
    auton_leave_starting_line:       Tinyint;
    auton_coral_scored_l4:           number;
    auton_coral_missed_l4:           number;
    auton_coral_scored_l3:           number;
    auton_coral_missed_l3:           number;
    auton_coral_scored_l2:           number;
    auton_coral_missed_l2:           number;
    auton_coral_scored_l1:           number;
    auton_coral_missed_l1:           number;
    auton_algae_scored_net:          number;
    auton_algae_missed_net:          number;
    auton_algae_scored_processor:    number;
    teleop_coral_scored_l4:          number;
    teleop_coral_missed_l4:          number;
    teleop_coral_scored_l3:          number;
    teleop_coral_missed_l3:          number;
    teleop_coral_scored_l2:          number;
    teleop_coral_missed_l2:          number;
    teleop_coral_scored_l1:          number;
    teleop_coral_missed_l1:          number;
    teleop_algae_missed_net:         number;
    teleop_algae_scored_net:         number;
    teleop_algae_scored_processor:   number;
    endgame_coral_intake_capability: string;
    endgame_algae_intake_capability: string;
    endgame_climb_successful:        Tinyint;
    endgame_climb_type:              string;
    endgame_climb_time:              string;
    overall_robot_died:              Tinyint;
    overall_defended_others:         Tinyint;
    overall_was_defended:            Tinyint;
    overall_defended:                string;
    overall_defended_by:             string;
    overall_pushing:                 number;
    overall_defense_quality:         number;
    overall_counter_defense:         number;
    overall_driver_skill:            number;
    overall_major_penalties:         number;
    overall_minor_penalties:         number;
    overall_penalties_incurred:      string;
    overall_comments:                string;
    robot_appeared:                  Tinyint;
};
export type StrategicEntry = {
    id:               number;
    match_event:      TbaApi.EventKey;
    team_number:      number;
    scouter_initials: string;
    comp_level:       TbaApi.Comp_Level;
    match_number:     number;
    robot_position:   TbaRequest.RobotPosition;
    comments:         string;
};
export type PitEntry = {
    id:                        number;
    match_event:               TbaApi.EventKey;
    team_number:               number;
    scouter_initials:          string;
    robot_weight:              number;
    drive_train_type:          string;
    motor_type:                string;
    number_of_motors:          number;
    wheel_type:                string;
    coral_intake_capability:   string;
    intake_width:              string;
    coral_scoring_l1:          Tinyint;
    coral_scoring_l2:          Tinyint;
    coral_scoring_l3:          Tinyint;
    coral_scoring_l4:          Tinyint;
    can_remove_algae:          Tinyint;
    algae_intake_capability:   string;
    algae_scoring_capability:  string;
    score_aiming_coral:        string;
    score_aiming_algae:        string;
    aiming_description:        string;
    climbing_capability:       string;
    pit_organization:          number;
    team_safety:               number;
    team_workmanship:          number;
    gracious_professionalism:  number;
    comments:                  string;
    robotImageURI:             string;
};
